class CommandError(Exception):
    pass

class ExistingResultError(Exception):
    pass
